#!/bin/sh
# Set up some common global variables

# Used internally
export DOTFILES_ROOT="$HOME/.dotfiles"

# Setup cli tools
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
export PATH="./bin:$HOME/bin:/usr/local/miniconda3/bin:/usr/local/bin:/usr/local/sbin:$PATH:/usr/local/texlive/2018/bin/x86_64-darwin"
export NOKOGIRI_USE_SYSTEM_LIBRARIES=1

# GitHub token with no scope, used to get around API limits
export HOMEBREW_GITHUB_API_TOKEN=$(cat ~/.token)

# Fix for global node modules
export NODE_PATH=./node_modules:/usr/local/lib/node_modules

# ZSH settings and initializations
export ZSH=$HOME/.oh-my-zsh
export SHELL=$(which zsh)
export ZSH_THEME="robbyrussell"
export DISABLE_UPDATE_PROMPT=true
export COMPLETION_WAITING_DOTS="true"
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Load private key passphrases from MacOS Keychain
{ eval `ssh-agent`; ssh-add -A;  } &>/dev/null

# You've got mail
unset MAILCHECK

# zsh-completions
fpath=(/usr/local/share/zsh-completions $fpath)
