#!/bin/bash

set -e

# Bootstrap dotfiles
if [[ ! -d "$HOME/.dotfiles" ]]; then
  git clone https://github.com/kyleniemeyer/dotfiles ~/.dotfiles
fi

# shellcheck source=lib/globals
source "$HOME/.dotfiles/lib/globals"

# shellcheck source=lib/functions
source "$DOTFILES_ROOT/lib/functions"

if [ "$TRAVIS" != "true" ]; then
  sudo -v
else
  sudo -n -v
fi

# bundler
setups=(symlinks token homebrew osx ruby dropbox dock background-apps zsh chrome atom mackup)

for setup in "${setups[@]}"; do
  script/title "Setting up $setup"
  "script/setup/$setup"
done

# Remove strap.sh, which contains tokens
rm -f "$HOME/Downloads/strap.sh"

script/title "Fin."
