#!/bin/bash
# Opens apps for the first time to start the setup process

apps=(EncryptMe Dropbox yubiswitch Yoink "Bartender 3" Backblaze)

exit 0

for app in "${apps[@]}"; do
  open "/Applications/$app.app"
done
