#!/bin/bash

# Remove all apps from the dock
dockutil --list | awk -F"\t" '{print $1}' | while read -r line; do
  dockutil --remove "$line"
done

# Give dock time to restart
sleep 1

# Apps wanted in the dock, in order
apps=(Safari Mail Messages Slack Keybase Tweetbot "Fantastical 2" Cardhop Notes "DEVONthink Pro Office" Things Zotero iTunes Photos iBooks)

# Re-add the apps we want
for app in "${apps[@]}"; do
  echo "adding $app to dock"
  dockutil --add "/Applications/$app.app"
  sleep 1
done
